### PR TITLE
Drop root privileges inside docker container

### PR DESCRIPTION
**Pull request by ailox**
Until now the binary inside the container was executed with root permissions. By adding an
unprivileged user, and switching to it on execution we can decrease the attack surface.

However, **I'm not completely sure this will not cause any problems** for existing users with already created data directories, as they will probably have been created with root permissions. As the user Account now has less privileges, it might not be able to read/write the existing files.

A fix for this is to run `chown -R 65534:65534 data/` to grant ownership to the unprivileged user.

### CODE REVIEW

**Comment by thinkberg** [comment]
This should be added to the docs for upgrades.

**Comment by ailox** [comment]
Is there already a upgrade section in the docs, that I am missing?

**Comment by leroxyl** [comment]
@ailox No, there is no upgrade section. It would be great if you could add the info in the https://github.com/ubirch/ubirch-client-go#run-client-in-docker-container section or create an upgrade section.

**Comment by thinkberg** [comment]
If we move from root to unprivileged the state file storage may be unreadable by the docker client, is that taken into account?

**Pull request closed without merging**
